name: PR Image

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-push-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive tags and repo
        id: meta
        run: |
          echo "repo_name=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_OUTPUT"
          echo "pr_tag=pr-${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          echo "sha_tag=pr-${{ github.event.pull_request.number }}-sha-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push PR images (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.meta.outputs.repo_name }}:${{ steps.meta.outputs.pr_tag }}
            ghcr.io/${{ github.repository_owner }}/${{ steps.meta.outputs.repo_name }}:${{ steps.meta.outputs.sha_tag }}
